name: metaboblend

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ 3.7, 3.8, 3.9 ]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup conda - Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: metaboblend
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          channels: anaconda, conda-forge

      - name: Install RI
        if: runner.os == 'Linux'
        shell: bash -l {0}
        run: |
          conda install -c conda-forge ri

      - name: Build MetaboBlend
        shell: bash -l {0}
        run: |
          python setup.py install
          metaboblend --help

      - name: Test with pytest-cov
        shell: bash -l {0}
        run: |
          conda install pytest codecov pytest-cov -c conda-forge
          pytest --cov ./ --cov-config=.coveragerc --cov-report=xml

      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          conda install flake8

          # stop build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Upload code coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          verbose: true
